---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: mongodb-secret
  namespace: startupservice
spec:
  encryptedData:
    MONGO_PASSWORD: AgCrMmHBDnSkwGRvwCrkgsZlOGouMFArkpn0uioP4uemcJ9RyTEihqM/PHtRDqbDp2y5EyImlCIwTqbGFrYQgTAA5m3nn9JgKTahyOxe9FWI4pwFDqyZlo3uSgLM11NU9qZlOE5eeh7s+SPjSbpQrnVGV43VsgsRUFsAI+e1QUtRQR+pZiq9n3MocPNobGDRMmEea035hE/O1ylUCwSsTy0CIBVfi/NdsIEuSZp7IFNctkLNG2/Bar3BS0kuPMT88WSbZPL8x0oO2QIRe64V8vouOQl139ec0XAoudymlZ3O9JxAtycsBk2fRanWMTYc7sTSXAXfCTkunrKSV+SfQpNuTyLDDEeoPqvbw3H3yVBjFXf00g08J5covlN6wZkvqtRp+xhS+cKzGzd/K/cvxelnl+CMKKGuODIkC6vwCHe1EnWU+pHvxeo0BUKj1uRlBwRhlDZcVu0sKBi7fiOfpAa5ntpQ3jReu3sUq21nCamI+0VXa1sxPUu0C6UVJtjqlSN57p5lstEpSl5hTBc3V6lc8j+lYJEzmW93Cnq/2JRZAQvUDN1iKAAYNqf8rmzCjLjws2ArFKeCp9MLEZTpfRtyFesUu1mAXUmd5AI6YDVKBZG3JF9G6D+aLpXSXKUb/g6RPPLqLFMcWQC4fKu/We+outrd9zK14qlI5ZcXnwFPVOc6l/f3J7x/ZnuheIkpKByyCpgHzv6FIg==
    MONGO_USER: AgBXK7bntqWFekib9sh5jAiBYdEabsWWiMIqf0bLXiO51UhSUeUS021f740VoBfxTt1Nw6d7trl03MXgvjCR2hD+VRZ6OYUPi6Chg2jWenSrCvVkWvS9r1z7pcSKej8lAbYl2tOK9IbI6SYJf+hWiqCkoDw+NADB2g35cIhxgkf6J1TRHkr1Ju97Vn4sjmE+kI56tLZ3Gj+M5a40UWHjx6p8kN+KAZirDFCRs5vh3p7tu5SIjbrS1w9dFvvUBeYT1kAfjWyFdvoRWe3FIZMgKPu0lPnaZX87F8MCwcOVEBbblw1GrqRM7XU7uu/iun+79WpDTi63QzOgJQ0wCnOUiUAJleGClewk/EnJUQ7ziBVDD0DZ1GMjecNvMwX8V+SVs4Ay8GrmKr2oxQMxXED+c02GWru1KSC08NjpZ22M78AH5G0ZnmSm9g4Jm6m0qLpU9BvUsH5eFecPxsajBMXjjrkpKCdDlMjAnORj/kAOVDD4KcWvTg94f1+/eX1t/NLPZ6t2Vj1a35eeBh3wiT9Xn7DigS20YgPJA5ACmxaqqhGUTtWKykoBwOwZoHP9WnQgiwDF948hX/frOU5tO1Gaj5HeiQFW+6SfWBXFGs0vByy7T9+0aaBtmVKfpT4OAiua+yMIApKbnlRD5QhEDnvt10LCbaQftc9vLZCqxK8IaNTYshJxvHF6EY84xs//kNQGMDyJfSOeKw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: mongodb-secret
      namespace: startupservice
    type: Opaque
