apiVersion: v1
kind: Service
metadata:
  name: kibana-external
  namespace: default        # Ingress와 같은 네임스페이스
spec:
  type: ExternalName
  externalName: kibana.elk.svc.cluster.local
  ports:
  - port: 5601
    targetPort: 5601