apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend-deployment
  namespace: frontend
  labels:
    app: react-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: react-frontend
          image: 590183915522.dkr.ecr.ap-northeast-2.amazonaws.com/frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_CHANNEL_KEY
              valueFrom:
                secretKeyRef:
                  name: front-credentials
                  key: REACT_APP_CHANNEL_KEY
            - name: REACT_APP_STORE_ID
              valueFrom:
                secretKeyRef:
                  name: front-credentials
                  key: REACT_APP_STORE_ID