# cd/argocd-applications.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: contractservice
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Picktartup/Picktartup-Integration-Test.git
    path: microservice/contractservice
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: contractservice
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---