apiVersion: v1
kind: Service
metadata:
  name: adminservice
  namespace: adminservice
  labels:
    app: adminservice
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: adminservice