apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: elk
data:
  elasticsearch.yml: |
    cluster.name: "docker-cluster"
    network.host: 0.0.0.0
    discovery.type: single-node
    
    # Security settings
    xpack.security.enabled: false
    xpack.security.enrollment.enabled: false
    xpack.security.transport.ssl.enabled: false
    xpack.security.http.ssl.enabled: false
    
    # Additional settings
    http.port: 9200
    http.host: 0.0.0.0
    transport.host: 0.0.0.0
    
    # Memory settings
    bootstrap.memory_lock: true