apiVersion: v1
kind: Service
metadata:
  name: coinservice
  namespace: coinservice
  labels:
    app: coinservice
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: coinservice