apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: contract-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Picktartup/Picktartup-Integration-Test.git
    targetRevision: main
    path: microservice/contractservice
  destination:
    server: https://kubernetes.default.svc
    namespace: contractservice
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Timeout=300s
  ignoreDifferences:                  
    - group: bitnami.com
      kind: SealedSecret
      jsonPointers:
        - /status