apiVersion: apps/v1
kind: Deployment
metadata:
  name: contractservice
  namespace: contractservice
  labels:
    app: contractservice
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contractservice
  template:
    metadata:
      labels:
        app: contractservice
    spec:
      imagePullSecrets:
        - name: ecr-secret
      initContainers:
        - name: check-db-ready
          image: postgres:13
          command: ['sh', '-c', 
            'until pg_isready -h contractservice-postgresql.contractservice.svc.cluster.local -p 5432;
            do echo waiting for database; sleep 2; done;']
      containers:
        - name: contractservice
          image: 590183915522.dkr.ecr.ap-northeast-2.amazonaws.com/contractservice:162130d
          volumeMounts:
            - name: keystore-volume
              mountPath: /app/keystore
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: contract-db-credentials
                  key: POSTGRES_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: contract-db-credentials
                  key: POSTGRES_DB
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: contract-db-credentials
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: contract-db-credentials
                  key: POSTGRES_PASSWORD
            - name: ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: contract-db-credentials
                  key: ACCESS_KEY
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: contract-db-credentials
                  key: SECRET_KEY
            # Added new environment variables from sealed secret
            - name: BSC_NETWORK_URL
              valueFrom:
                secretKeyRef:
                  name: contract-db-credentials
                  key: BSC_NETWORK_URL
            - name: CONTRACT_ADMIN_PRIVATEKEY
              valueFrom:
                secretKeyRef:
                  name: contract-db-credentials
                  key: CONTRACT_ADMIN_PRIVATEKEY
            - name: CONTRACT_FUNDING_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: contract-db-credentials
                  key: CONTRACT_FUNDING_ADDRESS
            - name: CONTRACT_TOKEN_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: contract-db-credentials
                  key: CONTRACT_TOKEN_ADDRESS
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            failureThreshold: 40
            periodSeconds: 10
      volumes:
        - name: keystore-volume
          persistentVolumeClaim:
            claimName: keystore-pvc