apiVersion: v1
kind: Service
metadata:
  name: contractservice
  namespace: contractservice
  labels:
    app: contractservice
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: contractservice
