apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keystore-pvc
  namespace: contractservice
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi