apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: userservice-postgresql
  namespace: userservice
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  serviceName: userservice-postgresql
  replicas: 1
  selector:
    matchLabels:
      app: userservice-postgresql
  template:
    metadata:
      labels:
        app: userservice-postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: user-db-credentials
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: user-db-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-db-credentials
                  key: POSTGRES_PASSWORD
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
            requests:
              memory: "512Mi"
              cpu: "250m"
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgresql-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "nfs-client"
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: userservice-postgresql
  namespace: userservice
  labels:
    app: userservice-postgresql
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: userservice-postgresql