---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-secret
  namespace: userservice
spec:
  encryptedData:
    REDIS_HOST: AgAbJ/0448/ubijR8003FhDf8j3P/EJK8csAKCF5HVn5SZMjJ1cFn/aJ8vvZKsf28irQ3qVLayapNMODQhDZvFOsyz+WnM7JeRz6siRBbe1ekgt6v6lseu7fIWmLlP2u4X7ZlnyC8ncSb1kRf4Gi8Bt8grErTaIo9HDgN6tPRz/Wv/O4b7YP8CvsEZPkplNDPLVgt/5PNWXgH1hwCwA/DrJkHHp3UrfkMgicJezf6lOHceLF8N0e256rttTi1YEG3ygjNW58zJxg6bX2HjjTTlEIoL0+h+MhXEVSKEt2Zs9XfqXrCHXYhrPKU963bjqZ5FVlSLTwbaCbeuwC/JtIywHt3XeyG5xdqosvrXuL5vQeHp/6phkQnRez7FsIIrNVyp3Vgx4gdtRsX7RAIOJpJZeKqPPr+SbEHwg1KX/yjIEPJEY7mcDkyXImv/G0OGwmw4KwmcnBqOIrdZxsYdAy303xRWmM8KK26nM6BZVh/oi/fqCa1g+SFiLyypXE1bbubXZJl9x+ebGFER8jWEnB1gny/43KBYMlcZeXlDfW1AK4fo4u+UZ3uw8WEcTTn2wSSVviHiWjdcPZljdH589AUoG0e07YJAVxgYGUXvQ0yffmaV+/uQp0MeikzZUMnPm174L+SsDuasZ6UDRgQN60yfo7y7jHsKUOqhiLEo6nd1Hqxpymyj0S4VdKVI0iKpg1bRxF3uTqeiipuZc1
    REDIS_PORT: AgBTtknzmgI++x426ymgG8oUIouqxVoVOB3ycffhNElLy64ySXmfILHECambOj+PUqdXx5Tl9SL+9gj1uepnV94jjRBusr1AQ2+ufjhn2BXuiKZeAQbHQ2uR2z+SScbzxZD0UlFCO1HJ692p43JD0LXMvk2HVeYLS5MmshFmaoOvfbUZnhNtBEP9zFipJzl0moRcGyu2Ww1awpdQAxHN5K/OGVbg2PvwZu24auljmkbWVBmrc4L5iZc6Lzcf9B7iAYwRCDkslvwOCoiIKE22E4J/kSo9FeLovxxok7YnfFTshvbIaF1MdbAbIDeeOnuG3qsiZGVQdXN4oBhWF82h7TM9Jfp/vZZu/qoS74y8JLsaw8q9XHQHrZPIi0uZR6smRq763ee+n77qXzoucwEqdy0XDBFyvL/uCewF04U8ckP+eBt5OjNdLFgCb46vYK48CdPyv5ILeS0A9mqsrhv6V1OiTGzk3fQwZGOnT0B/h+h6/ZWuh1Nt2GCFGyheHM+R+ZTAgmHUN9E6TGp9c7lEt0cTULQLoszAbOAYpvtEuTR14JSQyKx7FDUzqKTlYeBXYDr6bGzQRnRgekfP3v/nIbIbMdYWBdBnQqhXD38821L1CDXwQw+vKfIR2hhzXfb+FF9y8JwBsXPz4YL8oHYTr7Q0HKbKgjw1kI4sNY76/CCRE8O/peQs2ZOC56gQZXVe7tN4J5Fs
  template:
    metadata:
      creationTimestamp: null
      name: redis-secret
      namespace: userservice
    type: Opaque
