# walletservice namespace
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keystore-pvc
  namespace: walletservice
  annotations:
    nfs.io/storage-path: "/shared-keystore"  # 공통 경로 지정
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi