apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coinservice
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Picktartup/Picktartup-coinservice.git
    path: deploy/manifests
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: coinservice
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true