apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eks-startup-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Picktartup/Picktartup-Integration-Test.git
    targetRevision: main
    path: microservice/startupservice
  destination:
    server: https://B258BDF819F6764DABEAE042571E85C2.gr7.ap-northeast-2.eks.amazonaws.com
    namespace: startupservice
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Timeout=300s
  ignoreDifferences:                  
    - group: bitnami.com
      kind: SealedSecret
      jsonPointers:
        - /status