apiVersion: apps/v1
kind: Deployment
metadata:
  name: startupservice
  namespace: startupservice
  labels:
    app: startupservice
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: startupservice
  template:
    metadata:
      labels:
        app: startupservice
    spec:
      imagePullSecrets:
        - name: ecr-secret
      initContainers:
        - name: check-db-ready
          image: postgres:13
          command: ['sh', '-c', 
            'until pg_isready -h startupservice-postgresql.startupservice.svc.cluster.local -p 5432;
            do echo waiting for database; sleep 2; done;']
        - name: check-mongodb-ready
          image: mongo:6.0
          command: ['sh', '-c',
            'until mongosh --host mongodb.startupservice.svc.cluster.local:27017 --eval "db.adminCommand(\"ping\")" --quiet;
            do echo waiting for mongodb; sleep 2; done;']
      containers:
        - name: startupservice
          image: 590183915522.dkr.ecr.ap-northeast-2.amazonaws.com/startupservice:045ea66
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: startup-db-credentials
                  key: POSTGRES_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: startup-db-credentials
                  key: POSTGRES_DB
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: startup-db-credentials
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: startup-db-credentials
                  key: POSTGRES_PASSWORD
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: startup-db-credentials
                  key: AWS_ACCESS_KEY
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: startup-db-credentials
                  key: AWS_SECRET_KEY
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: startup-db-credentials
                  key: AWS_REGION
            - name: AWS_S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: startup-db-credentials
                  key: AWS_S3_BUCKET
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_USER
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: MONGO_PASSWORD
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            failureThreshold: 120
            periodSeconds: 10