apiVersion: v1
kind: Service
metadata:
  name: startupservice
  namespace: startupservice
  labels:
    app: startupservice
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: startupservice